sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t dockerhys/lecture7-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerhys/lecture7-practice npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-lecture7-react"
  env: "Dockerlecture7react-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-441181517960"
  bucket_path: "docker-lecture7-react"
  on:
    barnch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY