sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t dockerhys/lecture7-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerhys/lecture7-practice npm run test -- --coverage

after_success:
  - echo "Test Success"
